fixed path for direction delete surrounded variables in quotes added check for empty path

diff --git a/msync b/msync
--- a/msync
+++ b/msync
@@ -28,9 +28,9 @@ _CONFIG=$HOME/.msync
 
 # Create ~/.msync config if dosen't exist
 if [ ! -f $_CONFIG ]; then
-	touch $_CONFIG
-	echo "_SOURCE=" >> $_CONFIG
-	echo "_DEST=" >> $_CONFIG
+    touch $_CONFIG
+    echo "_SOURCE=" >> $_CONFIG
+    echo "_DEST=" >> $_CONFIG
 fi
 
 # Includes
@@ -48,30 +48,29 @@ fi
 # @return void
 ###
 clean() {
-
-	if [ ! -d $1 ]; then
-		echo "Error: Target path invalid $1"; exit 1
+	if [[ -z "$1" ]] || [ ! -d "$1" ]; then
+		echo "Error: Clean path invalid $1"; exit 1
 	fi
 
 	echo "######################################"
 	echo "# Scanning path to clean junk files"
 
-	#find $1 -name *.m3u -print0 | xargs -0 rm -rf
-	#find $1 -name ".DS_Store" -print0 | xargs -0 rm -rf
-	find $1 -name ".thumbnails" -print0 | xargs -0 rm -rf
-	find $1 -name ".webviews" -print0 | xargs -0 rm -rf
-	find $1 -name *.jpg -print0 | xargs -0 rm -rf
-	find $1 -name *.jpeg -print0 | xargs -0 rm -rf
-	find $1 -name *.png -print0 | xargs -0 rm -rf
-	find $1 -name *.txt -print0 | xargs -0 rm -rf
-	find $1 -name *.pdf -print0 | xargs -0 rm -rf
-	find $1 -name *.nfo -print0 | xargs -0 rm -rf
-	find $1 -name *.url -print0 | xargs -0 rm -rf
-	find $1 -name *.sfv -print0 | xargs -0 rm -rf
-	find $1 -name *.zip -print0 | xargs -0 rm -rf
-	find $1 -name *.cue -print0 | xargs -0 rm -rf
-	find $1 -name ._* -print0 | xargs -0 rm -rf
-	find . -type d -empty -exec echo Removing empty directory {} \; -exec rmdir {} \; 2> /dev/null
+	#find "$1" -name *.m3u -print0 | xargs -0 rm -rf
+	#find "$1" -name ".DS_Store" -print0 | xargs -0 rm -rf
+	find "$1" -name ".thumbnails" -print0 | xargs -0 rm -rf
+	find "$1" -name ".webviews" -print0 | xargs -0 rm -rf
+	find "$1" -name *.jpg -print0 | xargs -0 rm -rf
+	find "$1" -name *.jpeg -print0 | xargs -0 rm -rf
+	find "$1" -name *.png -print0 | xargs -0 rm -rf
+	find "$1" -name *.txt -print0 | xargs -0 rm -rf
+	find "$1" -name *.pdf -print0 | xargs -0 rm -rf
+	find "$1" -name *.nfo -print0 | xargs -0 rm -rf
+	find "$1" -name *.url -print0 | xargs -0 rm -rf
+	find "$1" -name *.sfv -print0 | xargs -0 rm -rf
+	find "$1" -name *.zip -print0 | xargs -0 rm -rf
+	find "$1" -name *.cue -print0 | xargs -0 rm -rf
+	find "$1" -name ._* -print0 | xargs -0 rm -rf
+	find "$1" -type d -empty -exec echo Removing empty directory {} \; -exec rmdir {} \; 2> /dev/null
 	echo "######################################"
 	echo ""
 }
@@ -85,8 +84,8 @@ clean() {
 ###
 convert() {
 
-	if [ ! -d $1 ]; then
-		echo "Error: Target path invalid $1"; exit 1
+	if [[ -z "$1" ]] || [ ! -d "$1" ]; then
+		echo "Error: Convert path invalid $1"; exit 1
 	fi
 
 	echo "######################################"
@@ -97,7 +96,7 @@ convert() {
 	# Root directory path
 	# @param string
 	###
-	_path=$1
+	_path="$1"
 
 	###
 	# MP3 encoding bitrate
@@ -105,7 +104,7 @@ convert() {
 	###
 	_bitrate=320k
 	if [[ $# -ge 2 ]]; then
-		_bitrate=$2
+		_bitrate="$2"
 	fi
 
 	###
@@ -114,13 +113,13 @@ convert() {
 	###
 	_delete_origional=true
 	if [[ $# -ge 3 ]]; then
-		_delete_origional=$3
+		_delete_origional="$3"
 	fi
 
 	_count=0
 
 	# @alt find -E $_path -type f -iregex '.*\.(flac|wma)$' | while read file; do
-	find $_path -type f -iname '*.flac' | while read file; do
+	find "$_path" -type f -iname '*.flac' | while read file; do
 
 		_filepath="${file%.[Ff][Ll][Aa][Cc]}"
 		_newfile="$_filepath.mp3"
@@ -132,7 +131,7 @@ convert() {
 		echo "# Converting: $file"
 		echo "# "
 
-		ffmpeg -i "$file" -ab $_bitrate -vsync 2 "$_newfile" < /dev/null > /dev/null
+		ffmpeg -i "$file" -ab "$_bitrate" -vsync 2 "$_newfile" < /dev/null > /dev/null
 		wait
 
 		[ "$_delete_origional" = false ] && continue
@@ -162,17 +161,17 @@ convert() {
 hash ffmpeg 2>/dev/null || { echo >&2 "Error: ffmpeg not found, aborting sync..."; exit 1; }
 
 if [[ -z "$_SOURCE" ]] || [ ! -d "$_SOURCE" ]; then
-	echo "Error: Source directory invalid $_SOURCE"
-	echo "Aborting source processing"
+    echo "Error: Source directory invalid $_SOURCE"
+    echo "Aborting source processing"
 else
-	convert "$_SOURCE"
-	clean "$_SOURCE"
+    convert "$_SOURCE"
+    clean "$_SOURCE"
 fi
 
 if [[ -z "$_DEST" ]] || [ ! -d "$_DEST" ]; then
-	echo "Error: destination directory invalid $_DEST"
-	echo "Aborting sync"
+    echo "Error: destination directory invalid $_DEST"
+    echo "Aborting sync"
 else
-	rsync -rvc --delete-before "$_SOURCE" "$_DEST"
-	clean "$_DEST"
+    rsync -rvc --delete-before "$_SOURCE" "$_DEST"
+    clean "$_DEST"
 fi
